Repository 41y08h/fquery, pull requests merged in 2023-11, with the labels that each got.

#7 bump dependencies to latest version and minor updates to documentation
  README.md
  example/.metadata
  example/lib/main.dart
  example/pubspec.yaml
  example/test/widget_test.dart
  lib/src/hooks/use_query.dart
  pubspec.yaml
Labels: documentation

#13 fix: run fetching when enabled option changed to true
  lib/src/observer.dart
Labels: bug

#12 feat: make refetch awaitable
  lib/src/hooks/use_query.dart
  lib/src/observer.dart
Labels: enhancement
